-- ELIMINACION DE TABLAS
DROP TABLE AEROPUERTO;
DROP TABLE AVION;
DROP TABLE BOLETA;
DROP TABLE CIUDAD;
DROP TABLE CLIENTE;
DROP TABLE COMPANIA;
DROP TABLE CREDITO;
DROP TABLE DEBITO;
DROP TABLE DESTINO;
DROP TABLE DETALLE_COMPRA;
DROP TABLE ENCUESTA;
DROP TABLE FORMA_PAGO;
DROP TABLE ITINERARIO;
DROP TABLE ORIGEN;
DROP TABLE PAIS;
DROP TABLE PASAJE;
DROP TABLE PASAJERO;
DROP TABLE VUELO;

-- CREACION DE TABLAS
CREATE TABLE AEROPUERTO
(
	ID_AEROPUERTO NVARCHAR2(50) NOT NULL,
	DIRECCION NVARCHAR2(50),
	CIUDAD NVARCHAR2(50),
	NOMBRE NVARCHAR2(50)
);

CREATE TABLE AVION
(
	ID_AVION NVARCHAR2(50) NOT NULL,
	MODELO NVARCHAR2(50),
	CAPACIDAD NUMBER,
	ANIO DATE
);

CREATE TABLE BOLETA
(
	ID_BOLETA NVARCHAR2(50) NOT NULL,
	CLIENTE NVARCHAR2(50),
	FECHA DATE,
	TOTAL NUMBER CHECK(TOTAL>0),
	HORA NUMBER,
	ESTADO NVARCHAR2(50),
	FORMA_DE_PAGO NVARCHAR2(50),
	DETALLE NVARCHAR2(50),
	ENCUESTA NVARCHAR2(50)
);

CREATE TABLE CIUDAD
(
	ID_CIUDAD NVARCHAR2(50) NOT NULL,
	NOMBRE NVARCHAR2(50),
	PAIS NVARCHAR2(50)
);

CREATE TABLE CLIENTE
(
	ID_CLIENTE NVARCHAR2(50) NOT NULL,
	NOMBRE NVARCHAR2(50),
	APELLIDO NVARCHAR2(50),
	FECHA_NACIMIENTO DATE,
	GENERO NVARCHAR2(50),
	TIPO_DOCUMENTO NVARCHAR2(50),
	FECHA_VENCIMIENTO_DOCUMENTO DATE,
	NUMERO_DOCUMENTO NUMBER,
	NACIONALIDAD NVARCHAR2(50), 
	PAIS NVARCHAR2(50),
	TELEFONO NVARCHAR2(50) UNIQUE,
	EMAIL NVARCHAR2(50) UNIQUE,
	CONSTRASENA NVARCHAR2(50)
);

CREATE TABLE COMPANIA
(
	ID_COMPANIA NVARCHAR2(50) NOT NULL,
	NOMBRE NVARCHAR2(50),
	DIRECCION NVARCHAR2(50),
	TELEFONO NVARCHAR2(50) UNIQUE,
	RUT NVARCHAR2(50) UNIQUE
);

CREATE TABLE CREDITO
(
	ID_CREDITO NVARCHAR2(50) NOT NULL,
	N_TARJETA NVARCHAR2(50) UNIQUE,
	FECHA_CADUCIDAD DATE,
	CVV NVARCHAR2(50),
	N_CUOTAS NUMBER,
	NOMBRE_TITULAR NVARCHAR2(50),
	CALLE NVARCHAR2(50),
	NUMERO NVARCHAR2(50),
	CIUDAD NVARCHAR2(50),
	PAIS NVARCHAR2(50)
);

CREATE TABLE DEBITO
(
	ID_DEBITO NVARCHAR2(50) NOT NULL,
	BANCO NVARCHAR2(50),
	RUT NVARCHAR2(50),
	N_TARJETA NVARCHAR2(50) UNIQUE,
	CONTRASENA NVARCHAR2(50)
);

CREATE TABLE DESTINO
(
	ID_DESTINO NVARCHAR2(50) NOT NULL,
	AEROPUERTO NVARCHAR2(50)
);

CREATE TABLE DETALLE_COMPRA
(
	ID_DETALLE NVARCHAR2(50) NOT NULL,
	PASAJE NVARCHAR2(50),
	TASAS NUMBER,
	COMPRA NVARCHAR2(50),
	CANTIDAD NUMBER,
	SUBTOTAL NUMBER
);

CREATE TABLE ENCUESTA
(
	ID_ENCUESTA NVARCHAR2(50) NOT NULL,
	VALORACION NVARCHAR2(50),
	SUGERENCIA NVARCHAR2(50)
);

CREATE TABLE FORMA_PAGO
(
	ID_PAGO NVARCHAR2(50) NOT NULL,
	NOMBRE NVARCHAR2(50),
	DEBITO NVARCHAR2(50),
	CREDITO NVARCHAR2(50)
);

CREATE TABLE ITINERARIO
(
	ID_ITINERARIO NVARCHAR2(50) NOT NULL,
	HORA NVARCHAR2(50),
	FECHA DATE,
	ORIGEN NVARCHAR2(50),
	DESTINO NVARCHAR2(50)
);

CREATE TABLE ORIGEN
(
	ID_ORIGEN NVARCHAR2(50) NOT NULL,
	AEROPUERTO NVARCHAR2(50)
);

CREATE TABLE PAIS
(
	ID_PAIS NVARCHAR2(50) NOT NULL,
	NOMBRE NVARCHAR2(50)
);

CREATE TABLE PASAJE
(
	ID_PASAJE NVARCHAR2(50) NOT NULL,
	CLASE NVARCHAR2(50),
	ASIENTO NVARCHAR2(50),
	VALOR NUMBER,
	VUELO NVARCHAR2(50),
	PASAJERO NVARCHAR2(50),
	DESCUENTO NUMBER
);

CREATE TABLE PASAJERO
(
	ID_PASAJERO NVARCHAR2(50) NOT NULL,
	NOMBRE NVARCHAR2(50),
	APELLIDO NVARCHAR2(50),
	FECHA_NACIMIENTO DATE,
	DOCUMENTO NVARCHAR2(50),
	N_DOCUMENTO NVARCHAR2(50),
	N_TELEFONO NVARCHAR2(50) UNIQUE,
	CORREO NVARCHAR2(50) UNIQUE,
	GENERO NVARCHAR2(50)
);

CREATE TABLE VUELO
(
	ID_VUELO NVARCHAR2(50) NOT NULL,
	CAPACIDAD NUMBER,
	NUMERO_VUELO NVARCHAR2(50),
	AVION NVARCHAR2(50),
	COMPANIA NVARCHAR2(50),
	ITINERARIO NVARCHAR2(50)
);

-- DEFINICION DE CLAVES PRIMARIAS
ALTER TABLE AEROPUERTO ADD CONSTRAINT PK_AEROPUERTO PRIMARY KEY (ID_AEROPUERTO);
ALTER TABLE AVION ADD CONSTRAINT PK_AVION PRIMARY KEY (ID_AVION);
ALTER TABLE BOLETA ADD CONSTRAINT PK_BOLETA PRIMARY KEY (ID_BOLETA);
ALTER TABLE CIUDAD ADD CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE);
ALTER TABLE COMPANIA ADD CONSTRAINT PK_COMPANIA PRIMARY KEY (ID_COMPANIA);
ALTER TABLE CREDITO ADD CONSTRAINT PK_CREDITO PRIMARY KEY (ID_CREDITO);
ALTER TABLE DEBITO ADD CONSTRAINT PK_DEBITO PRIMARY KEY (ID_DEBITO);
ALTER TABLE DESTINO ADD CONSTRAINT PK_DESTINO PRIMARY KEY (ID_DESTINO);
ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT PK_DETALLE_COMPRA PRIMARY KEY (ID_DETALLE);
ALTER TABLE ENCUESTA ADD CONSTRAINT PK_ENCUESTA PRIMARY KEY (ID_ENCUESTA);
ALTER TABLE FORMA_PAGO ADD CONSTRAINT PK_FORMA_PAGO PRIMARY KEY (ID_PAGO);
ALTER TABLE ITINERARIO ADD CONSTRAINT PK_ITINERARIO PRIMARY KEY (ID_ITINERARIO);
ALTER TABLE ORIGEN ADD CONSTRAINT PK_ORIGEN PRIMARY KEY (ID_ORIGEN);
ALTER TABLE PAIS ADD CONSTRAINT PK_PAIS PRIMARY KEY (ID_PAIS);
ALTER TABLE PASAJE ADD CONSTRAINT PK_PASAJE PRIMARY KEY (ID_PASAJE);
ALTER TABLE PASAJERO ADD CONSTRAINT PK_PASAJERO PRIMARY KEY (ID_PASAJERO);
ALTER TABLE VUELO ADD CONSTRAINT PK_VUELO PRIMARY KEY (ID_VUELO);

-- DEFINICION DE CLAVES FORANEAS
ALTER TABLE AEROPUERTO ADD CONSTRAINT FK_AEROPUERTO_CIUDAD FOREIGN KEY (CIUDAD) REFERENCES CIUDAD (ID_CIUDAD) ON DELETE CASCADE;
ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE;
ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA_ENCUESTA FOREIGN KEY (ENCUESTA) REFERENCES ENCUESTA (ID_ENCUESTA) ON DELETE CASCADE;
ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA_DETALLE FOREIGN KEY (DETALLE) REFERENCES DETALLE_COMPRA (ID_DETALLE) ON DELETE CASCADE;
ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA_PAGO FOREIGN KEY (FORMA_DE_PAGO) REFERENCES FORMA_PAGO (ID_PAGO) ON DELETE CASCADE;
ALTER TABLE CIUDAD ADD CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (PAIS) REFERENCES PAIS (ID_PAIS) ON DELETE CASCADE;
ALTER TABLE CREDITO ADD CONSTRAINT FK_CREDITO_PAIS FOREIGN KEY (PAIS) REFERENCES PAIS (ID_PAIS) ON DELETE CASCADE;
ALTER TABLE CREDITO ADD CONSTRAINT FK_CREDITO_CIUDAD FOREIGN KEY (CIUDAD) REFERENCES CIUDAD (ID_CIUDAD) ON DELETE CASCADE;
ALTER TABLE DESTINO ADD CONSTRAINT FK_DESTINO_AEROPUERTO FOREIGN KEY (AEROPUERTO) REFERENCES AEROPUERTO (ID_AEROPUERTO) ON DELETE CASCADE;
ALTER TABLE DETALLE_COMPRA ADD CONSTRAINT FK_DETALLE_PASAJE FOREIGN KEY (PASAJE) REFERENCES PASAJE (ID_PASAJE) ON DELETE CASCADE;
ALTER TABLE FORMA_PAGO ADD CONSTRAINT FK_PAGO_DEBITO FOREIGN KEY (DEBITO) REFERENCES DEBITO (ID_DEBITO) ON DELETE CASCADE;
ALTER TABLE FORMA_PAGO ADD CONSTRAINT FK_PAGO_CREDITO FOREIGN KEY (CREDITO) REFERENCES CREDITO (ID_CREDITO) ON DELETE CASCADE;
ALTER TABLE ITINERARIO ADD CONSTRAINT FK_ITINERARIO_DESTINO FOREIGN KEY (DESTINO) REFERENCES DESTINO (ID_DESTINO) ON DELETE CASCADE;
ALTER TABLE ITINERARIO ADD CONSTRAINT FK_ITINERARIO_ORIGEN FOREIGN KEY (ORIGEN) REFERENCES ORIGEN (ID_ORIGEN) ON DELETE CASCADE;
ALTER TABLE PASAJE ADD CONSTRAINT FK_PASAJE_VUELO FOREIGN KEY (VUELO) REFERENCES VUELO (ID_VUELO) ON DELETE CASCADE;
ALTER TABLE PASAJE ADD CONSTRAINT FK_PASAJE_PASAJERO FOREIGN KEY (PASAJERO) REFERENCES PASAJERO (ID_PASAJERO) ON DELETE CASCADE;
ALTER TABLE VUELO ADD CONSTRAINT FK_VUELO_AVION FOREIGN KEY (AVION) REFERENCES AVION (ID_AVION) ON DELETE CASCADE;
ALTER TABLE VUELO ADD CONSTRAINT FK_VUELO_COMPANIA FOREIGN KEY (COMPANIA) REFERENCES COMPANIA (ID_COMPANIA) ON DELETE CASCADE;
ALTER TABLE VUELO ADD CONSTRAINT FK_VUELO_ITINERARIO FOREIGN KEY (ITINERARIO) REFERENCES ITINERARIO (ID_ITINERARIO) ON DELETE CASCADE;